### ISSUE TITLE
Bro, when can I use it

### ISSUE THREAD

**Issue by 1042932843** [MuNgLo/MDunGen#1]

**Comment by MuNgLo** [comment]
Oh sorry for not keeping track. I went a bit deep on this and took a break. Just getting my gear setup again and fixing logins and stuff.
Should be getting back to it soon. Using it would depend kinda on what you wanna use it for but usability needs work for sure. Been focusing on the functionality and layout of how the generation happens.
Keep an eye on my twitch channel. That is where I will be when working on it. 
https://www.twitch.tv/munglo
